:PROPERTIES:
:ID:       154691ca-1744-4bdb-bf08-000f707d1005
:END:
#+title: 2026-02-16
#+filetags: daily

* Bible Reading
** Genesis 41:17-42:17

God protects Joseph through establishing gifts within him. He does the same for us.

Why does Joseph test his brothers?

** Matthew 13:24-46

The parables of Jesus, establish stories and myth as the methodology of developing the abstract concepts of God's will.

It refers to the weeds as everything that causes sin and all who do evil, what exactly does this mean? Everyone does evil and
everyone has within that which tempts them. Taking out the "weeds" prematurely will destroy the wheat.

The final stories is about how the kingdom of God gives everything for the grace of those who are lost.
** Psalm 18:1-15
Love of God
** Proverbs 4:1-6
Community, family, and God fosters wisdom. Wisdom that protects you.

* Today
Today was a good day. While I wasn't feeling my absolute best, I was productive. Not as in I did much work, but I was able to actively engage in things I enjoy. I wrote a large section on the fundamentals of metaphysics, some other things, got back into reading the bible, and read from Numerical Hamiltonian Problems.

The main thing was the writing, it has been a while sense I have been able to have sustained effort on such a complex and in-depth subject. Much of my stuff is rederived, but that is kinda the point.
