name: Compile LaTeX
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install TeXlive
        run: sudo apt-get update && sudo apt-get install -y texlive-full
      - name: Compile LaTeX
        run: pdflatex main.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: document
          path: document.pdf
